# Generated by Django 5.2.9 on 2025-12-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='사용자 이메일 (중복 불가)', max_length=254, unique=True)),
                ('code', models.CharField(help_text='8자리 영문 대문자+숫자 리딤코드', max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
            ],
        ),
    ]
