# Generated by Django 5.2.9 on 2025-12-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redactor_pro_code_issuance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemcode',
            name='is_used',
            field=models.BooleanField(default=False, help_text='사용 여부'),
        ),
    ]
