# Generated by Django 5.2.9 on 2025-12-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redactor_pro_code_issuance', '0002_redeemcode_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemcode',
            name='email',
            field=models.EmailField(help_text='사용자 이메일', max_length=254),
        ),
    ]
