# Generated by Django 5.2.9 on 2025-12-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redactor_pro_code_issuance', '0003_alter_redeemcode_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemcode',
            name='uuid',
            field=models.CharField(blank=True, help_text='사용자 기기 UUID', max_length=100, null=True),
        ),
    ]
