# Generated by Django 5.2.9 on 2025-12-13 07:01

from django.db import migrations, models


def migrate_is_used_to_status(apps, schema_editor):
    """is_used 값을 status로 변환"""
    RedeemCode = apps.get_model('redactor_pro_code_issuance', 'RedeemCode')
    # is_used=True -> status='used'
    RedeemCode.objects.filter(is_used=True).update(status='used')
    # is_used=False -> status='unused' (default이므로 이미 적용됨)


def migrate_status_to_is_used(apps, schema_editor):
    """status 값을 is_used로 역변환 (롤백용)"""
    RedeemCode = apps.get_model('redactor_pro_code_issuance', 'RedeemCode')
    RedeemCode.objects.filter(status='used').update(is_used=True)
    RedeemCode.objects.exclude(status='used').update(is_used=False)


class Migration(migrations.Migration):

    dependencies = [
        ('redactor_pro_code_issuance', '0004_redeemcode_uuid'),
    ]

    operations = [
        # 1. 먼저 status 필드 추가 (is_used 필드 유지)
        migrations.AddField(
            model_name='redeemcode',
            name='status',
            field=models.CharField(
                choices=[('unused', '미사용'), ('used', '사용됨'), ('deleted', '삭제됨')],
                default='unused',
                help_text='상태 (unused: 미사용, used: 사용됨, deleted: 삭제됨)',
                max_length=10
            ),
        ),
        # 2. 데이터 마이그레이션
        migrations.RunPython(migrate_is_used_to_status, migrate_status_to_is_used),
        # 3. is_used 필드 삭제
        migrations.RemoveField(
            model_name='redeemcode',
            name='is_used',
        ),
    ]
