# Generated by Django 5.1.4 on 2025-01-14 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCupInfo',
            fields=[
                ('worldCupId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='')),
                ('totalRound', models.IntegerField(default=4)),
                ('image', models.TextField(default='')),
                ('createdDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorldCupItem',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.TextField(default='')),
                ('description', models.CharField(max_length=200)),
                ('worldCupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_worldcup.worldcupinfo')),
            ],
        ),
    ]
