# Generated by Django 5.1.4 on 2025-01-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_worldcup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldcupinfo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='worldcupitem',
            name='image',
        ),
        migrations.AddField(
            model_name='worldcupinfo',
            name='infoImage',
            field=models.ImageField(blank=True, upload_to='images/info/'),
        ),
        migrations.AddField(
            model_name='worldcupitem',
            name='itemImage',
            field=models.ImageField(blank=True, upload_to='images/items/'),
        ),
    ]
